name: Deploy OfferTracker

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        cd backend && npm ci
        cd ../offertracker_fronted && npm ci
    
    - name: Build project
      run: |
        cd backend && npm run build
        cd ../offertracker_fronted && npm run build

  # 部署作业需要手动配置以下GitHub Secrets：
  # CLOUDFLARE_API_TOKEN: 您的Cloudflare API令牌
  # CLOUDFLARE_ACCOUNT_ID: 您的Cloudflare账户ID
  
  deploy-backend:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    
    - name: Install backend dependencies
      run: cd backend && npm ci
    
    - name: Deploy backend to Cloudflare
      run: cd backend && npm run deploy
      env:
        # 请在GitHub仓库设置中配置这些secrets
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: offertracker_fronted/package-lock.json
    
    - name: Install frontend dependencies
      run: cd offertracker_fronted && npm ci
    
    - name: Build frontend
      run: cd offertracker_fronted && npm run build
    
    - name: Deploy frontend to Cloudflare Pages
      run: cd offertracker_fronted && npm run deploy
      env:
        # 请在GitHub仓库设置中配置这些secrets
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        # 配置前端环境变量
        VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
        VITE_S3_BASE_URL: ${{ secrets.VITE_S3_BASE_URL }}